version: '2'
services:
  librarius-app:
    image: librarius
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATA_MONGODB_URI=mongodb://librarius-mongodb:27017
      - SPRING_DATA_MONGODB_DATABASE=librarius
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - SPRING_DATA_JEST_URI=http://librarius-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://librarius-elasticsearch:9200
    ports:
      - 8080:8080
  librarius-mongodb:
    extends:
      file: mongodb.yml
      service: librarius-mongodb
  librarius-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: librarius-elasticsearch
